#version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
#      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - C:/Users/Vagelis/Desktop/postgresql_data:/var/lib/postgresql/data
#      - C:/Users/Vagelis/Documents/postgresql_data/test:/var/lib/postgresql/data
    env_file:
      - .env.postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      start_period: 30s

  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: app_keycloak
    command: [ "start-dev", "--import-realm" ]
    env_file:
      - .env.keycloak
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - postgres
    ports:
      - 8080:8080

  db:
    image: postgres:15
    container_name: vet-db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env.postgresql.app.db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - C:/Users/Vagelis/Desktop/app-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  pgadmin-data:
  db:


# #if page not log in not fund say try ths   http://localhost:8080/admin/master/console/